Algoritmo "Habilitado"
// Disciplina: PA
// Professora: Edilma Bindá
// Turma: 1°C Grupo B
// Nome: Raphaela Rodrigues Luvizotto
// Data atual  : 25/05/2023
Var
idade: real

//Entrada
Inicio
escreval ("Começou!")
escreval("Qual a sua idade?")
leia(idade)

//Processamento
se idade >= 18 entao
escreval("Ok, pode passar")
senao
escreval ("Você não pode dirigir!")
fimse

//Saída
escreval ("Acabou!")

Fimalgoritmo