Algoritmo "Conversão de Real em Dolar"
//Disciplina: PA
// Professora: Edilma Bindá
// Turma: 1°C Grupo B
// Nome: Raphaela Rodrigues Luvizotto
// Data: 30/03/2023
Var
vdolar, vreal, cotacao: real

//entrada
Inicio
escreval ("Digite o valor em real: ")
leia (vreal)

escreval ("Digite a cotação do dolar do dia: ")
leia (cotacao)

//processamento
vdolar <- vreal/cotacao

//saída
escreval ("O valor em dolar é: ", vdolar)


Fimalgoritmo