Algoritmo "Positivo e negativo"
// Disciplina: PA
// Professora: Edilma Bindá
// Turma: 1°C Grupo B
// Nome: Raphaela Rodrigues Luvizotto
// Data atual  : 25/05/2023
Var
valors, valorm: real

//Entrada
Inicio
escreval ("Digite o valor do seu salário: ")
leia(valors)
escreval ("Digite seu valor mensal: ")
leia(valorm)

//Processamento e saída
se valors < valorm entao
escreval("Saldo negativo")
senao
escreval("Saldo positivo")
fimse


Fimalgoritmo