Algoritmo "Temperatura"
// Disciplina: PA
// Professora: Edilma Bindá
// Turma: 1°C Grupo B
// Nome: Raphaela Rodrigues Luvizotto
// Data atual  : 25/05/2023

Var
temperatura: real

//Entrada
Inicio
escreval ("Digite a temperatura: ")
leia(temperatura)


//Processamento e saída
se temperatura < 20 entao
escreval("Está frio")
senao
se temperatura < 25 entao
escreval("Está normal")
senao
escreval ("Está quente")
fimse

Fimalgoritmo