Algoritmo "Temperatura"
// Disciplina: PA
// Professora: Edilma Bindá
// Turma: 1°C Grupo B
// Nome: Raphaela Rodrigues Luvizotto
// Data : 02/06/2023


Var
tempe: real

//Entrada
Inicio

escreval ("Digite a temperatura: ")
  leia(tempe)

//Processamento e saída

se(tempe<20) entao
  escreval("Está frio")
fimse

se ((tempe >=20)e(tempe<25)) entao
  escreval("Está normal")
fimse

se (tempe>=25) entao
  escreval ("Está quente")
fimse

fimalgoritmo

