Algoritmo "Maior ou menor de idade"
// Disciplina: PA
// Professora: Edilma Bindá
// Turma: 1°C Grupo B
// Nome: Raphaela Rodrigues Luvizotto
// Data atual  : 25/05/2023
Var
nome: caractere
idade: real

//Entrada
Inicio
escreval ("Digite o seu nome: ")
leia(nome)
escreval ("Digite sua idade: ")
leia(idade)

//Processamento e saída
se idade >= 18 entao
escreval(nome, " você é maior de idade")
senao
escreval(nome, " você é menor de idade")
fimse


Fimalgoritmo