Algoritmo "Valor entre 100 e 200"
// Disciplina: PA
// Professora: Edilma Bindá
// Turma: 1°C Grupo B
// Nome: Raphaela Rodrigues Luvizotto
// Data atual  : 25/05/2023

Var
numero: real

//Entrada
Inicio
escreval ("Digite um número:")
leia(numero)

//Processamento e saída
se numero > 100 entao
e
se numero < 200 entao
escreval(numero, " está no intervalo.")
fimse

Fimalgoritmo
fimse